### ISSUE TITLE
For linux?

### ISSUE THREAD

**Issue by peylight** [ZeqMacaw/Crowbar#9]
Hi
How can i use it in Unix OS, like Debian?

**Comment by 0Curtain0** [comment]
@peylight 
Hey, any luck running Crowbar with Steam Play (Proton)?

**Comment by mirh** [comment]
It runs just fine out of the box in wine-staging, not sure why you didn't even try. 

The problem is, there's no native version of many tools. So this has to be windows-only at least until somebody port them. 
https://github.com/ValveSoftware/source-sdk-2013/issues/340
https://github.com/ValveSoftware/source-sdk-2013/issues/141
